##
## Name: docker-lemp-5.5.0
## Dockerfile to build a LAMP and Node stack image
## Author: https://about.me/henrycv
##
## MAINTAINER Henry Carbajal <entidad.estelar@gmail.com>
##

version: "3.1"
services:

  mysql:
    image: mysql:5.6
    container_name: docker-lemp-5.5.0-mysql
    volumes:
      - /var/www/html:/var/www/html
      - .:/docker-lemp-5.5.0
    working_dir: /var/www/html
    environment:
      # - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - docker-lemp-5.5.0-net

  node:
    build:
      context: .
      dockerfile: node/Dockerfile
    container_name: docker-lemp-5.5.0-node
    volumes:
      - /var/www/html:/var/www/html
      - .:/docker-lemp-5.5.0
    working_dir: /var/www/html
    environment:
      # - NODE_ENV=production
      - NODE_ENV=development
    # volumes:
    #   - ./:/usr/src/app
    expose:
      - "8080"
    networks:
      - docker-lemp-5.5.0-net


  nginx:
    image: nginx:latest
    container_name: docker-lemp-5.5.0-nginx
    ports:
      - "8080:80"
    volumes:
      - /var/www/html:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
    networks:
      - docker-lemp-5.5.0-net

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: docker-lemp-5.5.0-php
    volumes:
      - /var/www/html:/var/www/html
      - .:/docker-lemp-5.5.0
      - /var/log/nginx:/var/log/nginx
      - ./php/php.ini-development:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    environment:
      - DOCKERIZED=1
    depends_on:
      - mysql
      - node
    restart: always
    networks:
      - docker-lemp-5.5.0-net

networks:
  docker-lemp-5.5.0-net:
    driver: bridge