##
## Name: docker-lemp-5.5.0
## Dockerfile to build a LAMP and Node stack image
## Author: https://about.me/henrycv
##
## MAINTAINER Henry Carbajal <entidad.estelar@gmail.com>
##

version: "3.1"
services:

  nginx:
    image: nginx:1.10.2
    container_name: docker-lemp-5.5.0-nginx
    restart: always
    links:
      - php
      - node
    volumes:
      - /var/www/html:/var/www/html/:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    working_dir: /var/www/html
    ports:
      - 80:80
      - 443:443
    networks:
      - docker-lemp-5.5.0-net

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: docker-lemp-5.5.0-php
    restart: always
    volumes:
      - /var/www/html:/var/www/html
      - .:/docker-lemp-5.5.0
      - ./php/php.ini-development:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - DB_NAME=lemp_bdd
      - TABLE_PREFIX=lemp_
      - DB_HOST=lemp
      - DB_PASSWORD=password
    networks:
      - docker-lemp-5.5.0-net

  mysql:
    image: mysql:5.6
    container_name: docker-lemp-5.5.0-mysql
    restart: always
    volumes:
      - /var/www/html:/var/www/html
      - .:/docker-lemp-5.5.0
    working_dir: /docker-lemp-5.5.0
    environment:
      # - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - docker-lemp-5.5.0-net

  node:
    build:
      context: .
      dockerfile: node/Dockerfile
    container_name: docker-lemp-5.5.0-node
    restart: always
    volumes:
      - /var/www/html:/var/www/html
      - .:/docker-lemp-5.5.0
    working_dir: /docker-lemp-5.5.0
    environment:
      # - NODE_ENV=production
      - NODE_ENV=development
    expose:
      - "8080"
    networks:
      - docker-lemp-5.5.0-net

networks:
  docker-lemp-5.5.0-net:
    driver: bridge